# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudUsach'
    organization: 'devsecops-usach-v2'
    projectKey: 'DevSecOps-USACH-v2_pet-clinic'
    projectName: 'pet-clinic'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: dependency-check-build-task@6
  inputs:
    projectName: 'pet-clinic'
    scanPath: '$(Build.Sources.Directory)/build/libs'
    format: 'HTML'